"""Ren'Py engine (dialogue-oriented extract + sidecar apply)."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

from handoffkit_localize.engines.base import AnalyzeReport, StringRow

# Dialogue-ish string literals in .rpy
STR_RE = re.compile(
    r'(?:^|\s)(?:[a-zA-Z_][\w]*\s+)?"((?:\\.|[^"\\]){2,})"',
    re.MULTILINE,
)
SKIP_PREFIXES = ("gui.", "config.", "build.", "define translate")


def _sid(s: str) -> str:
    return hashlib.sha1(s.encode("utf-8")).hexdigest()[:12]


class RenpyEngine:
    name = "renpy"

    def detect(self, root: Path) -> AnalyzeReport | None:
        rpy = list(root.rglob("*.rpy"))
        if not rpy and not (root / "game").is_dir():
            return None
        if not rpy:
            return None
        samples = [str(p.relative_to(root)) for p in rpy[:15]]
        return AnalyzeReport(
            engine="renpy",
            confidence=0.9,
            game_root=str(root.resolve()),
            data_dirs=["game"] if (root / "game").is_dir() else [],
            extractable_globs=["**/*.rpy"],
            skip_globs=["**/*.rpyc", "**/cache/**", "**/saves/**"],
            notes=[
                "Extracts string literals from .rpy (heuristic).",
                "Apply writes JSON sidecars under game/tl/<lang>/handoffkit_strings.json.",
                "Prefer Ren'Py official translate for production; this is a bootstrap.",
            ],
            sample_files=samples,
            recommended_pipeline=[
                "extract .rpy strings",
                "translate",
                "apply sidecar + manual integrate if needed",
            ],
            supports_apply=True,
        )

    def extract(self, root: Path) -> list[StringRow]:
        seen: dict[str, StringRow] = {}
        for fp in root.rglob("*.rpy"):
            if any(x in fp.parts for x in ("cache", "saves", "tmp")):
                continue
            try:
                text = fp.read_text(encoding="utf-8", errors="replace")
            except Exception:
                continue
            rel = str(fp.relative_to(root))
            for m in STR_RE.finditer(text):
                s = m.group(1).encode("utf-8").decode("unicode_escape")
                if len(s.strip()) < 2:
                    continue
                if s.startswith(SKIP_PREFIXES):
                    continue
                if not re.search(r"[A-Za-z\u00C0-\u024F\u3400-\u9fff]", s):
                    continue
                sid = _sid(s)
                if sid not in seen:
                    seen[sid] = StringRow(id=sid, text=s, files=[rel], chars=len(s))
                elif rel not in seen[sid].files:
                    seen[sid].files.append(rel)
        return sorted(seen.values(), key=lambda r: (-r.chars, r.id))

    def apply(
        self,
        root: Path,
        lang: str,
        mapping: dict[str, str],
        *,
        source_lang: str = "en",
    ) -> dict[str, Any]:
        import json

        out_dir = root / "game" / "tl" / lang
        out_dir.mkdir(parents=True, exist_ok=True)
        # reverse mapping: we store id->tr externally; mapping here is en->tr
        path = out_dir / "handoffkit_strings.json"
        path.write_text(
            json.dumps(mapping, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        readme = out_dir / "README_HANDOFFKIT.txt"
        readme.write_text(
            "Generated by handoffkit-localize (public).\n"
            "Merge these strings into Ren'Py translate blocks as needed.\n",
            encoding="utf-8",
        )
        return {"files_written": 1, "pack": str(path)}
