#pragma once

/// Umbrella header for the HandoffKit C++ **runtime core** (no demos/fusion/browser).
/// For web search/explore/scrape use <handoffkit/browser.hpp> or link handoffkit::browser.
#include <handoffkit/error.hpp>
#include <handoffkit/handoff.hpp>
#include <handoffkit/version.hpp>
#include <handoffkit/core/quality.hpp>
#include <handoffkit/core/validation.hpp>
#include <handoffkit/csp/contracts.hpp>
#include <handoffkit/csp/artifact_security.hpp>
#include <handoffkit/csp/native_compute.hpp>
#include <handoffkit/csp/security.hpp>
#include <handoffkit/csp/os_keystore.hpp>
#include <handoffkit/csp/durable_scheduler.hpp>
#include <handoffkit/csp/dispatcher.hpp>
#include <handoffkit/csp/secure_memory.hpp>
#include <handoffkit/csp/tls_transport.hpp>
#include <handoffkit/evaluation/workflow_eval.hpp>
#include <handoffkit/io/html_report.hpp>
#include <handoffkit/io/reports.hpp>
#include <handoffkit/runtime/agent.hpp>
#include <handoffkit/runtime/builtin_tools.hpp>
#include <handoffkit/runtime/echo_provider.hpp>
#include <handoffkit/runtime/fallback_provider.hpp>
#include <handoffkit/runtime/http_provider.hpp>
#include <handoffkit/runtime/providers.hpp>
#include <handoffkit/runtime/memory.hpp>
#include <handoffkit/runtime/orchestrator.hpp>
#include <handoffkit/runtime/protocol.hpp>
#include <handoffkit/runtime/provider.hpp>
#include <handoffkit/runtime/replay.hpp>
#include <handoffkit/runtime/structured.hpp>
#include <handoffkit/runtime/team.hpp>
#include <handoffkit/runtime/tool.hpp>
#include <handoffkit/runtime/trace.hpp>
#include <handoffkit/util/text.hpp>
#include <handoffkit/workflows/recipe.hpp>
#include <handoffkit/workflows/templates.hpp>
#include <handoffkit/train/types.hpp>
#include <handoffkit/train/dataset.hpp>
#include <handoffkit/train/distill.hpp>
#include <handoffkit/train/backend.hpp>
#include <handoffkit/train/runner.hpp>
