export const RECORDED_FIXTURE_ID = "clinical-recorded-run-v1";

export const RECORDED_RUN = Object.freeze({
  contract_version: "1.20.0-alpha.2",
  run_id: "run-recorded-fixture-v1",
  experience: "professional",
  track: "closed_sequential",
  phase: "closed",
  status: "complete",
  blind_id: "pro-sandbox-001",
  opening:
    "De-identified sandbox case. Adult, 41 years old, hybrid office work and weekly regional flights. Mid-winter. Day 0 sore throat and fatigue after a 3.5 hour flight; day 1 myalgias and fever 38.4 C; day 3 dry cough, consumer SpO2 97-98%; day 4 fever 37.6 C, no chest pain, no hemoptysis, no confusion. No PCR, antigen, CBC, or imaging yet.",
  actions: [
    {
      action_id: "act-recorded-001",
      name: "ask_question",
      query: "history of present illness",
      idempotency_key: "act-recorded-001",
      role: "",
    },
    {
      action_id: "act-recorded-002",
      name: "submit_diagnosis",
      query: "Influenza-like illness",
      idempotency_key: "act-recorded-002",
      role: "",
    },
  ],
  observations: [
    {
      observation_id: "obs-recorded-001",
      action_id: "act-recorded-001",
      section: "history",
      content: "Post-flight winter onset over four days with fever then lingering dry cough. No known household test-positive contact.",
      code: "",
      source_hash: "recorded",
      source_fragment: "Post-flight winter onset over four days with fever then lingering dry cough.",
      resource_units: 1,
    },
    {
      observation_id: "obs-recorded-002",
      action_id: "act-recorded-002",
      section: "diagnosis_submission",
      content: "Diagnosis submitted.",
      code: "",
      source_hash: "",
      source_fragment: "",
      resource_units: 0,
    },
  ],
  differential: [],
  budget_units: 40,
  spent_units: 1,
  max_rounds: 12,
  rounds: 2,
  diagnosis: "Influenza-like illness",
  score: {
    correct: false,
    judge_scores: [],
    alias_match: true,
    exact_match: true,
    complete: true,
    quorum: 0,
    clinical_validity: null,
    heuristic_only: true,
    scoring_mode: "gold_replay",
  },
  error: null,
  replay: true,
  scoring_eligible: true,
  status_public: "experimental / research and education only / not clinically validated",
  locale: "en",
  evidence: {
    sections: {
      history: "Post-flight winter onset over four days with fever then lingering dry cough. No known household test-positive contact.",
    },
  },
  revision: 2,
  source: "recorded_fixture",
  fixture_id: "clinical-recorded-run-v1",
});
