# CMake generated Testfile for 
# Source directory: C:/Hijosdelsol/handoffkit/packages/cpp-ml
# Build directory: C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_smoke "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_smoke.exe")
  set_tests_properties(test_ml_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;92;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_smoke "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_smoke.exe")
  set_tests_properties(test_ml_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;92;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_smoke "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_smoke.exe")
  set_tests_properties(test_ml_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;92;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_smoke "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_smoke.exe")
  set_tests_properties(test_ml_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;92;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_smoke NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_ops "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_ops.exe")
  set_tests_properties(test_ml_ops PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;93;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_ops "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_ops.exe")
  set_tests_properties(test_ml_ops PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;93;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_ops "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_ops.exe")
  set_tests_properties(test_ml_ops PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;93;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_ops "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_ops.exe")
  set_tests_properties(test_ml_ops PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;93;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_ops NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_sft "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_sft.exe")
  set_tests_properties(test_ml_sft PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;94;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_sft "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_sft.exe")
  set_tests_properties(test_ml_sft PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;94;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_sft "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_sft.exe")
  set_tests_properties(test_ml_sft PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;94;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_sft "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_sft.exe")
  set_tests_properties(test_ml_sft PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;94;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_sft NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_lora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_lora.exe")
  set_tests_properties(test_ml_lora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;95;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_lora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_lora.exe")
  set_tests_properties(test_ml_lora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;95;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_lora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_lora.exe")
  set_tests_properties(test_ml_lora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;95;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_lora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_lora.exe")
  set_tests_properties(test_ml_lora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;95;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_lora NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_preference "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_preference.exe")
  set_tests_properties(test_ml_preference PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;96;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_preference "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_preference.exe")
  set_tests_properties(test_ml_preference PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;96;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_preference "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_preference.exe")
  set_tests_properties(test_ml_preference PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;96;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_preference "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_preference.exe")
  set_tests_properties(test_ml_preference PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;96;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_preference NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_quant "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_quant.exe")
  set_tests_properties(test_ml_quant PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;97;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_quant "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_quant.exe")
  set_tests_properties(test_ml_quant PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;97;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_quant "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_quant.exe")
  set_tests_properties(test_ml_quant PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;97;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_quant "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_quant.exe")
  set_tests_properties(test_ml_quant PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;97;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_quant NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_attn_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_attn_parity.exe")
  set_tests_properties(test_ml_attn_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;98;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_attn_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_attn_parity.exe")
  set_tests_properties(test_ml_attn_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;98;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_attn_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_attn_parity.exe")
  set_tests_properties(test_ml_attn_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;98;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_attn_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_attn_parity.exe")
  set_tests_properties(test_ml_attn_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;98;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_attn_parity NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_bpe "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_bpe.exe")
  set_tests_properties(test_ml_bpe PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;99;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_bpe "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_bpe.exe")
  set_tests_properties(test_ml_bpe PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;99;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_bpe "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_bpe.exe")
  set_tests_properties(test_ml_bpe PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;99;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_bpe "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_bpe.exe")
  set_tests_properties(test_ml_bpe PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;99;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_bpe NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_gguf "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_gguf.exe")
  set_tests_properties(test_ml_gguf PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;100;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_gguf "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_gguf.exe")
  set_tests_properties(test_ml_gguf PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;100;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_gguf "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_gguf.exe")
  set_tests_properties(test_ml_gguf PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;100;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_gguf "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_gguf.exe")
  set_tests_properties(test_ml_gguf PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;100;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_gguf NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_kernels "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_kernels.exe")
  set_tests_properties(test_ml_kernels PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;101;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_kernels "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_kernels.exe")
  set_tests_properties(test_ml_kernels PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;101;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_kernels "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_kernels.exe")
  set_tests_properties(test_ml_kernels PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;101;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_kernels "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_kernels.exe")
  set_tests_properties(test_ml_kernels PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;101;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_kernels NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_qlora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_qlora.exe")
  set_tests_properties(test_ml_qlora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;102;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_qlora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_qlora.exe")
  set_tests_properties(test_ml_qlora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;102;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_qlora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_qlora.exe")
  set_tests_properties(test_ml_qlora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;102;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_qlora "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_qlora.exe")
  set_tests_properties(test_ml_qlora PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;102;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_qlora NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_dist "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_dist.exe")
  set_tests_properties(test_ml_dist PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;103;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_dist "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_dist.exe")
  set_tests_properties(test_ml_dist PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;103;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_dist "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_dist.exe")
  set_tests_properties(test_ml_dist PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;103;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_dist "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_dist.exe")
  set_tests_properties(test_ml_dist PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;103;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_dist NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_base_load "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_base_load.exe")
  set_tests_properties(test_ml_base_load PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;104;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_base_load "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_base_load.exe")
  set_tests_properties(test_ml_base_load PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;104;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_base_load "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_base_load.exe")
  set_tests_properties(test_ml_base_load PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;104;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_base_load "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_base_load.exe")
  set_tests_properties(test_ml_base_load PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;104;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_base_load NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ml_cuda_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Debug/test_ml_cuda_parity.exe")
  set_tests_properties(test_ml_cuda_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;105;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ml_cuda_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/Release/test_ml_cuda_parity.exe")
  set_tests_properties(test_ml_cuda_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;105;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ml_cuda_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/MinSizeRel/test_ml_cuda_parity.exe")
  set_tests_properties(test_ml_cuda_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;105;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ml_cuda_parity "C:/Hijosdelsol/handoffkit/packages/cpp-ml/build-cuda/RelWithDebInfo/test_ml_cuda_parity.exe")
  set_tests_properties(test_ml_cuda_parity PROPERTIES  _BACKTRACE_TRIPLES "C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;90;add_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;105;hk_ml_test;C:/Hijosdelsol/handoffkit/packages/cpp-ml/CMakeLists.txt;0;")
else()
  add_test(test_ml_cuda_parity NOT_AVAILABLE)
endif()
