"""Tiny calculator CLI generated by HandoffKit."""

from __future__ import annotations

import argparse
from collections.abc import Sequence


def add(left: float, right: float) -> float:
    """Return left plus right."""
    return left + right


def subtract(left: float, right: float) -> float:
    """Return left minus right."""
    return left - right


def multiply(left: float, right: float) -> float:
    """Return left multiplied by right."""
    return left * right


def divide(left: float, right: float) -> float:
    """Return left divided by right."""
    if right == 0:
        raise ValueError("Cannot divide by zero.")
    return left / right


OPERATIONS = {
    "add": add,
    "subtract": subtract,
    "multiply": multiply,
    "divide": divide,
}


def calculate(operation: str, left: float, right: float) -> float:
    """Run one named calculator operation."""
    try:
        function = OPERATIONS[operation]
    except KeyError as exc:
        raise ValueError(f"Unknown operation: {operation}") from exc
    return function(left, right)


def main(argv: Sequence[str] | None = None) -> int:
    """Parse CLI arguments and print the calculated result."""
    parser = argparse.ArgumentParser(description="Tiny calculator CLI.")
    parser.add_argument("operation", choices=sorted(OPERATIONS))
    parser.add_argument("left", type=float)
    parser.add_argument("right", type=float)
    args = parser.parse_args(argv)

    result = calculate(args.operation, args.left, args.right)
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
