"""Command-line interface (thin facade; implementation in handoffkit._cli)."""

from __future__ import annotations

from handoffkit._cli.demos import (
    evaluate_report,
    list_provider_models,
    list_providers,
    list_showcases,
    probe_provider_models,
    render_report,
    run_api,
    run_async_demo,
    run_coding_review_demo,
    run_demo,
    run_doctor,
    run_doctor_benchmark_demo,
    run_doctor_orchestrator_demo,
    run_extension_demo,
    run_fusion_style_demo,
    run_independent_benchmark_demo,
    run_mai_style_doctor_benchmark_demo,
    run_named_showcase,
    run_provider_formats_demo,
    run_provider_tools_demo,
    run_quality_demo,
    run_recipe_demo,
    run_replay_demo,
    run_research_workflow_demo,
    run_structured_demo,
    run_support_escalation_demo,
    run_trace_demo,
    run_validators_demo,
    select_provider_model,
    validate_report,
)
from handoffkit._cli.main import main
from handoffkit._cli.media import (
    build_media_demo_report,
    inspect_media_transcript,
    list_media_ops_text,
    plan_media_dubbing,
    run_media_context_demo,
    run_media_demo,
    run_media_pipeline_plan,
)
from handoffkit._cli.project import (
    create_extension,
    delete_key,
    init_project,
    init_project_interactive,
    list_keys,
    load_dynamic_extensions,
    set_key,
    write_project_report,
)

__all__ = [
    "main",
    "run_demo",
    "run_async_demo",
    "run_recipe_demo",
    "run_extension_demo",
    "run_structured_demo",
    "run_provider_tools_demo",
    "run_quality_demo",
    "run_validators_demo",
    "run_provider_formats_demo",
    "run_doctor",
    "run_api",
    "run_trace_demo",
    "run_replay_demo",
    "validate_report",
    "evaluate_report",
    "render_report",
    "list_showcases",
    "list_providers",
    "list_provider_models",
    "probe_provider_models",
    "select_provider_model",
    "run_named_showcase",
    "run_coding_review_demo",
    "run_support_escalation_demo",
    "run_research_workflow_demo",
    "run_doctor_benchmark_demo",
    "run_mai_style_doctor_benchmark_demo",
    "run_independent_benchmark_demo",
    "run_doctor_orchestrator_demo",
    "run_fusion_style_demo",
    "build_media_demo_report",
    "run_media_demo",
    "inspect_media_transcript",
    "plan_media_dubbing",
    "list_media_ops_text",
    "run_media_pipeline_plan",
    "run_media_context_demo",
    "init_project",
    "init_project_interactive",
    "set_key",
    "delete_key",
    "list_keys",
    "write_project_report",
    "create_extension",
    "load_dynamic_extensions",
]

if __name__ == "__main__":
    raise SystemExit(main())
