"""Small project templates for starting HandoffKit workflows."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


def _json_default(value: Any) -> Any:
    """Return readable JSON fallback for non-serializable values."""
    if hasattr(value, "to_dict"):
        return value.to_dict()
    return str(value)


@dataclass
class TemplateFile:
    """One file generated by a project template."""

    path: str
    content: str

    def to_dict(self) -> dict[str, Any]:
        """Serialize this file."""
        return {"path": self.path, "content": self.content}


@dataclass
class ProjectTemplate:
    """A reusable HandoffKit project template."""

    name: str
    description: str
    files: list[TemplateFile] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize this template."""
        return {
            "name": self.name,
            "description": self.description,
            "files": [item.to_dict() for item in self.files],
            "metadata": self.metadata,
        }

    def to_json(self, *, indent: int | None = 2) -> str:
        """Serialize this template as JSON."""
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent, default=_json_default)

    def to_markdown(self) -> str:
        """Serialize this template as Markdown."""
        files = "\n".join(f"- `{item.path}`" for item in self.files) or "- none"
        return (
            f"# Project Template: {self.name}\n\n"
            f"## Description\n\n{self.description}\n\n"
            f"## Files\n\n{files}\n"
        )


@dataclass
class ScaffoldResult:
    """Result returned by TemplateScaffolder."""

    template: str
    root: str
    files_written: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    success: bool = True

    def to_dict(self) -> dict[str, Any]:
        """Serialize this scaffold result."""
        return {
            "template": self.template,
            "root": self.root,
            "files_written": self.files_written,
            "skipped": self.skipped,
            "success": self.success,
        }

    def to_json(self, *, indent: int | None = 2) -> str:
        """Serialize this scaffold result as JSON."""
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent)

    def to_markdown(self) -> str:
        """Serialize this scaffold result as Markdown."""
        written = "\n".join(f"- `{path}`" for path in self.files_written) or "- none"
        skipped = "\n".join(f"- `{path}`" for path in self.skipped) or "- none"
        return (
            "# Scaffold Result\n\n"
            f"## Template\n\n{self.template}\n\n"
            f"## Root\n\n{self.root}\n\n"
            f"## Files Written\n\n{written}\n\n"
            f"## Skipped\n\n{skipped}\n"
        )


class TemplateScaffolder:
    """Generate small HandoffKit starter projects from built-in templates."""

    def __init__(self, templates: list[ProjectTemplate] | None = None) -> None:
        self._templates = {
            template.name: template for template in (templates or builtin_templates())
        }

    def list_templates(self) -> list[str]:
        """Return available template names."""
        return sorted(self._templates)

    def get(self, name: str) -> ProjectTemplate:
        """Return one template by name."""
        try:
            return self._templates[name]
        except KeyError as exc:
            available = ", ".join(self.list_templates())
            raise KeyError(f"Unknown template {name!r}. Available templates: {available}") from exc

    def scaffold(
        self,
        project_name: str,
        *,
        template: str = "basic-agent",
        output: str | Path = ".",
        force: bool = False,
    ) -> ScaffoldResult:
        """Write a project template under output/project_name."""
        if not project_name.strip():
            raise ValueError("project_name must be a non-empty string.")
        selected = self.get(template)
        root = (Path(output) / project_name).resolve()
        root.mkdir(parents=True, exist_ok=True)
        files_written: list[str] = []
        skipped: list[str] = []

        for item in selected.files:
            destination = (root / item.path).resolve()
            if not self._within(destination, root):
                raise ValueError(f"template file escapes output directory: {item.path}")
            if destination.exists() and not force:
                skipped.append(str(destination))
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(
                item.content.replace("{{ project_name }}", project_name),
                encoding="utf-8",
            )
            files_written.append(str(destination))
        return ScaffoldResult(
            template=selected.name,
            root=str(root),
            files_written=files_written,
            skipped=skipped,
            success=not skipped,
        )

    def _within(self, path: Path, root: Path) -> bool:
        try:
            path.relative_to(root)
        except ValueError:
            return False
        return True


def builtin_templates() -> list[ProjectTemplate]:
    """Return built-in offline starter templates."""
    return [
        _basic_agent_template(),
        _coding_review_template(),
        _team_workflow_template(),
        _tool_agent_template(),
        _recipe_workflow_template(),
        _support_escalation_template(),
        _research_workflow_template(),
    ]


def _readme(title: str, description: str, command: str) -> str:
    return (
        f"# {title}\n\n"
        f"{description}\n\n"
        "## Run\n\n"
        "```powershell\n"
        f"{command}\n"
        "```\n"
    )


def _basic_agent_template() -> ProjectTemplate:
    return ProjectTemplate(
        name="basic-agent",
        description="Minimal single-agent HandoffKit starter.",
        files=[
            TemplateFile(
                "README.md",
                _readme(
                    "{{ project_name }}",
                    "A minimal HandoffKit agent project.",
                    "python main.py",
                ),
            ),
            TemplateFile(
                "main.py",
                (
                    "from handoffkit import Agent\n\n"
                    "agent = Agent('Planner', 'Create concise implementation plans.')\n"
                    "print(agent.run('Plan a tiny Python CLI.'))\n"
                ),
            ),
        ],
    )


def _team_workflow_template() -> ProjectTemplate:
    return ProjectTemplate(
        name="team-workflow",
        description="Sequential multi-agent workflow starter.",
        files=[
            TemplateFile(
                "README.md",
                _readme(
                    "{{ project_name }}",
                    "A HandoffKit Architect -> Coder -> Tester starter.",
                    "python team_workflow.py",
                ),
            ),
            TemplateFile(
                "team_workflow.py",
                (
                    "from handoffkit import Agent, HandoffProtocol, Team\n\n"
                    "team = Team(\n"
                    "    [\n"
                    "        Agent('Architect', 'Plan the implementation.'),\n"
                    "        Agent('Coder', 'Implement from handoff state.'),\n"
                    "        Agent('Tester', 'Review and test the result.'),\n"
                    "    ],\n"
                    "    protocol=HandoffProtocol(mode='hybrid_state'),\n"
                    ")\n"
                    "result = team.run('Create a small CLI calculator.')\n"
                    "print(result.final_output)\n"
                ),
            ),
        ],
    )


def _tool_agent_template() -> ProjectTemplate:
    return ProjectTemplate(
        name="tool-agent",
        description="Agent with a local Python tool.",
        files=[
            TemplateFile(
                "README.md",
                _readme(
                    "{{ project_name }}",
                    "A HandoffKit tool execution starter.",
                    "python tool_agent.py",
                ),
            ),
            TemplateFile(
                "tool_agent.py",
                (
                    "from handoffkit import Agent, tool\n\n"
                    "@tool\n"
                    "def add(a: int, b: int) -> int:\n"
                    "    return a + b\n\n"
                    "agent = Agent('Calculator', 'Use tools for arithmetic.', tools=[add])\n"
                    "report = agent.run_with_tools('call add with a=2 and b=3')\n"
                    "print(report.to_markdown())\n"
                ),
            ),
        ],
    )


def _recipe_workflow_template() -> ProjectTemplate:
    return ProjectTemplate(
        name="recipe-workflow",
        description="Reusable recipe workflow starter.",
        files=[
            TemplateFile(
                "README.md",
                _readme(
                    "{{ project_name }}",
                    "A HandoffKit recipe starter.",
                    "python recipe_workflow.py",
                ),
            ),
            TemplateFile(
                "recipe_workflow.py",
                (
                    "from handoffkit import Agent, RecipeRunner, WorkflowTemplate\n\n"
                    "recipe = WorkflowTemplate.plan_execute_review(\n"
                    "    name='plan-execute-review',\n"
                    "    task='Create a release checklist.',\n"
                    "    planner=Agent('Planner', 'Plan work.'),\n"
                    "    executor=Agent('Executor', 'Execute work.'),\n"
                    "    reviewer=Agent('Reviewer', 'Review work.'),\n"
                    ")\n"
                    "result = RecipeRunner(recipe).run()\n"
                    "print(result.to_markdown())\n"
                ),
            ),
        ],
    )


def _showcase_template(
    *,
    name: str,
    title: str,
    description: str,
    script: str,
) -> ProjectTemplate:
    return ProjectTemplate(
        name=name,
        description=description,
        files=[
            TemplateFile(
                "README.md",
                (
                    f"# {title}\n\n"
                    f"{description}\n\n"
                    "## Run\n\n"
                    "```bash\n"
                    f"python {script}\n"
                    "handoffkit report runs/latest\n"
                    "```\n"
                ),
            ),
            TemplateFile(
                script,
                (
                    "from handoffkit import run_showcase\n\n\n"
                    "if __name__ == '__main__':\n"
                    f"    result = run_showcase('{name}')\n"
                    "    print(result.to_markdown())\n"
                ),
            ),
        ],
    )


def _coding_review_template() -> ProjectTemplate:
    return _showcase_template(
        name="coding-review",
        title="Coding Agents Showcase",
        description="Architect -> Coder -> Reviewer -> Tester with structured handoffs.",
        script="coding_review.py",
    )


def _support_escalation_template() -> ProjectTemplate:
    return _showcase_template(
        name="support-escalation",
        title="Support Escalation Showcase",
        description="Triage -> Billing -> Refund -> Supervisor with audit-ready state.",
        script="support_escalation.py",
    )


def _research_workflow_template() -> ProjectTemplate:
    return _showcase_template(
        name="research-workflow",
        title="Research Workflow Showcase",
        description="Researcher -> Extractor -> Fact-checker -> Writer with traceable sources.",
        script="research_workflow.py",
    )
