"""Run a real multi-agent HandoffKit task and write reproducible reports."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent
from typing import Any

from handoffkit import Agent, HandoffProtocol
from handoffkit.errors import ProviderConfigurationError, ProviderExecutionError
from handoffkit.providers import EchoProvider, OpenAIProvider, choose_openai_compatible_model

ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = ROOT / "examples" / "output" / "calculator_cli"
REPORTS_DIR = ROOT / "reports"
MARKDOWN_REPORT = REPORTS_DIR / "real_task_calculator.md"
JSON_REPORT = REPORTS_DIR / "real_task_calculator.json"
TASK = (
    "Create a tiny Python CLI calculator with add, subtract, multiply and divide "
    "operations, plus tests."
)


@dataclass
class ProviderChoice:
    """Provider selected for the demo."""

    provider: Any
    label: str
    model: str
    model_endpoint_ok: bool
    available_models: list[str]
    selection_error: str


def choose_provider() -> ProviderChoice:
    """Use gpt-5.4 through an OpenAI-compatible endpoint, or fall back locally."""
    api_key = os.getenv("OPENAI_API_KEY")
    base_url = os.getenv("OPENAI_BASE_URL", "https://api.freemodel.dev/v1")
    if not api_key:
        return ProviderChoice(
            provider=EchoProvider(model="echo"),
            label="EchoProvider",
            model="echo",
            model_endpoint_ok=False,
            available_models=[],
            selection_error="OPENAI_API_KEY is not set; using deterministic local provider.",
        )

    try:
        selection = choose_openai_compatible_model(
            api_key=api_key,
            base_url=base_url,
            fallback_models=("gpt-5.4", "gpt-4o-mini"),
            timeout=30,
        )
        return ProviderChoice(
            provider=OpenAIProvider(
                api_key=api_key,
                base_url=selection.base_url,
                model=selection.model,
                timeout=60,
            ),
            label="OpenAIProvider",
            model=selection.model,
            model_endpoint_ok=selection.models_endpoint_ok,
            available_models=selection.available_models,
            selection_error="",
        )
    except (ProviderConfigurationError, ProviderExecutionError) as exc:
        return ProviderChoice(
            provider=EchoProvider(model="echo"),
            label="EchoProvider",
            model="echo",
            model_endpoint_ok=False,
            available_models=[],
            selection_error=f"OpenAI-compatible provider unavailable: {exc}",
        )


def reset_output_dir() -> None:
    """Create a clean generated-project folder."""
    if OUTPUT_DIR.exists():
        try:
            shutil.rmtree(OUTPUT_DIR)
        except PermissionError:
            pass
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def write_project_files() -> list[Path]:
    """Write the generated calculator CLI project."""
    calculator = OUTPUT_DIR / "calculator.py"
    calculator.write_text(
        dedent(
            '''
            """Tiny calculator CLI generated by HandoffKit."""

            from __future__ import annotations

            import argparse
            from collections.abc import Sequence


            def add(left: float, right: float) -> float:
                """Return left plus right."""
                return left + right


            def subtract(left: float, right: float) -> float:
                """Return left minus right."""
                return left - right


            def multiply(left: float, right: float) -> float:
                """Return left multiplied by right."""
                return left * right


            def divide(left: float, right: float) -> float:
                """Return left divided by right."""
                if right == 0:
                    raise ValueError("Cannot divide by zero.")
                return left / right


            OPERATIONS = {
                "add": add,
                "subtract": subtract,
                "multiply": multiply,
                "divide": divide,
            }


            def calculate(operation: str, left: float, right: float) -> float:
                """Run one named calculator operation."""
                try:
                    function = OPERATIONS[operation]
                except KeyError as exc:
                    raise ValueError(f"Unknown operation: {operation}") from exc
                return function(left, right)


            def main(argv: Sequence[str] | None = None) -> int:
                """Parse CLI arguments and print the calculated result."""
                parser = argparse.ArgumentParser(description="Tiny calculator CLI.")
                parser.add_argument("operation", choices=sorted(OPERATIONS))
                parser.add_argument("left", type=float)
                parser.add_argument("right", type=float)
                args = parser.parse_args(argv)

                result = calculate(args.operation, args.left, args.right)
                print(result)
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            '''
        ).lstrip(),
        encoding="utf-8",
    )

    tests = OUTPUT_DIR / "test_calculator.py"
    tests.write_text(
        dedent(
            '''
            """Tests for the generated calculator CLI."""

            from __future__ import annotations

            import calculator
            import pytest


            def test_operations() -> None:
                assert calculator.add(2, 3) == 5
                assert calculator.subtract(7, 2) == 5
                assert calculator.multiply(4, 3) == 12
                assert calculator.divide(8, 2) == 4


            def test_divide_by_zero() -> None:
                with pytest.raises(ValueError, match="Cannot divide by zero"):
                    calculator.divide(1, 0)


            def test_calculate_rejects_unknown_operation() -> None:
                with pytest.raises(ValueError, match="Unknown operation"):
                    calculator.calculate("power", 2, 3)


            def test_cli_main_outputs_result(capsys: pytest.CaptureFixture[str]) -> None:
                assert calculator.main(["multiply", "6", "7"]) == 0
                assert capsys.readouterr().out.strip() == "42.0"
            '''
        ).lstrip(),
        encoding="utf-8",
    )

    readme = OUTPUT_DIR / "README.md"
    readme.write_text(
        dedent(
            """
            # Calculator CLI

            Tiny calculator CLI generated by the HandoffKit real task demo.

            ## Usage

            ```bash
            python calculator.py add 2 3
            python calculator.py divide 8 2
            ```

            ## Test

            ```bash
            python -m pytest -q
            ```
            """
        ).lstrip(),
        encoding="utf-8",
    )
    return [calculator, tests, readme]


def run_generated_tests() -> dict[str, Any]:
    """Run pytest for the generated project and capture evidence."""
    command = [sys.executable, "-m", "pytest", "-q"]
    completed = subprocess.run(
        command,
        cwd=OUTPUT_DIR,
        env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
        capture_output=True,
        text=True,
        check=False,
    )
    return {
        "command": " ".join(command),
        "cwd": str(OUTPUT_DIR),
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def make_agents(choice: ProviderChoice) -> tuple[Agent, Agent, Agent, Agent]:
    """Create the agent chain used by the demo."""
    provider = choice.provider
    model = choice.model
    return (
        Agent(
            "Architect",
            "Plan implementation and state transfer.",
            model=model,
            provider=provider,
        ),
        Agent(
            "Coder",
            "Implement code from structured handoff state.",
            model=model,
            provider=provider,
        ),
        Agent("Tester", "Run tests and summarize verification.", model=model, provider=provider),
        Agent(
            "Reporter",
            "Turn evidence into reproducible reports.",
            model=model,
            provider=provider,
        ),
    )


def run_agent_flow(choice: ProviderChoice, files_created: list[Path]) -> dict[str, Any]:
    """Run Architect -> Coder -> Tester -> Reporter using HandoffState."""
    protocol = HandoffProtocol(mode="hybrid_state")
    architect, coder, tester, reporter = make_agents(choice)

    architect_output = architect.run(
        "Plan a tiny Python calculator CLI with add, subtract, multiply, divide, and tests."
    )
    coder_state = protocol.transfer(
        from_agent=architect,
        to_agent=coder,
        task=TASK,
        summary=architect_output,
        decisions=[
            "Expose calculator operations as pure functions.",
            "Use argparse for the CLI entry point.",
            "Keep generated tests next to the generated calculator module.",
        ],
        important_files=[str(path.relative_to(ROOT)) for path in files_created],
        next_steps=[
            "Write calculator.py.",
            "Write pytest coverage.",
            "Run generated project tests.",
        ],
        metadata={"stage": "architect_to_coder"},
    ).validate()

    coder_output = coder.run(
        "Implement the calculator project from the structured handoff.",
        handoff_state=coder_state,
    )
    tester_state = protocol.transfer(
        from_agent=coder,
        to_agent=tester,
        task=TASK,
        summary=coder_output,
        decisions=coder_state.decisions
        + ["Keep implementation dependency-free and deterministic."],
        important_files=coder_state.important_files,
        next_steps=["Run pytest in the generated project.", "Capture command evidence."],
        metadata={"stage": "coder_to_tester"},
    ).validate()

    test_result = run_generated_tests()
    tester_output = tester.run(
        "Review the pytest result and report whether the generated project passed.",
        handoff_state=tester_state,
    )
    reporter_state = protocol.transfer(
        from_agent=tester,
        to_agent=reporter,
        task=TASK,
        summary=tester_output,
        decisions=tester_state.decisions
        + [f"Generated project pytest return code: {test_result['returncode']}."],
        important_files=tester_state.important_files
        + [
            str(MARKDOWN_REPORT.relative_to(ROOT)),
            str(JSON_REPORT.relative_to(ROOT)),
        ],
        errors=[] if test_result["returncode"] == 0 else ["Generated project tests failed."],
        next_steps=[
            "Write Markdown report.",
            "Write JSON report.",
            "Include captured command evidence.",
        ],
        metadata={"stage": "tester_to_reporter"},
    ).validate()

    reporter_output = reporter.run(
        "Create reproducible reports from the handoff evidence.",
        handoff_state=reporter_state,
    )
    return {
        "protocol": protocol,
        "agents": (architect, coder, tester, reporter),
        "agent_outputs": {
            "architect": architect_output,
            "coder": coder_output,
            "tester": tester_output,
            "reporter": reporter_output,
        },
        "handoffs": [coder_state, tester_state, reporter_state],
        "test_result": test_result,
    }


def write_reports(
    *,
    choice: ProviderChoice,
    flow: dict[str, Any],
    files_created: list[Path],
) -> dict[str, Any]:
    """Write Markdown and JSON reports for the real task."""
    test_result = flow["test_result"]
    final_status = "passed" if test_result["returncode"] == 0 else "failed"
    relative_files = [str(path.relative_to(ROOT)) for path in files_created]
    commands = [
        {
            "command": test_result["command"],
            "cwd": test_result["cwd"],
            "returncode": test_result["returncode"],
            "stdout": test_result["stdout"],
            "stderr": test_result["stderr"],
        }
    ]
    handoff_dicts = [state.to_dict() for state in flow["handoffs"]]
    data = {
        "task": TASK,
        "provider": choice.label,
        "model": choice.model,
        "protocol": "hybrid_state",
        "agents": ["Architect", "Coder", "Tester", "Reporter"],
        "handoffs": handoff_dicts,
        "files_created": relative_files
        + [
            str(MARKDOWN_REPORT.relative_to(ROOT)),
            str(JSON_REPORT.relative_to(ROOT)),
        ],
        "commands_executed": commands,
        "test_result": {
            "returncode": test_result["returncode"],
            "stdout": test_result["stdout"],
            "stderr": test_result["stderr"],
        },
        "final_status": final_status,
    }
    JSON_REPORT.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

    architect_decisions = "\n".join(f"- {item}" for item in handoff_dicts[0]["decisions"])
    files_list = "\n".join(f"- {item}" for item in data["files_created"])
    handoff_flow = "\n".join(
        f"- {item['from_agent']} -> {item['to_agent']}: {item['summary'].splitlines()[0]}"
        for item in handoff_dicts
    )
    limitations = [
        "Generated calculator scope is intentionally tiny.",
        "The demo uses EchoProvider when no API key is configured.",
    ]
    if choice.selection_error:
        limitations.append(choice.selection_error)
    limitations_text = "\n".join(f"- {item}" for item in limitations)
    next_improvements = "\n".join(
        [
            "- Add packaging metadata for the generated calculator.",
            "- Add more CLI edge case tests.",
            "- Compare EchoProvider output with OpenAI-compatible provider output.",
        ]
    )
    stdout_block = test_result["stdout"].strip() or "(empty)"
    stderr_block = test_result["stderr"].strip() or "(empty)"

    markdown = f"""# HandoffKit Real Task Report: Calculator CLI

## Task

{TASK}

## Provider used

{choice.label}

## Model used

{choice.model}

## Protocol used

hybrid_state

## Agents

- Architect
- Coder
- Tester
- Reporter

## Handoff flow

{handoff_flow}

## Architect decisions

{architect_decisions}

## Coder implementation summary

The Coder agent received structured state and produced a dependency-free Python
calculator CLI with pure operation functions, an argparse entry point, and pytest
coverage.

## Tester results

Return code: {test_result["returncode"]}

## Files created

{files_list}

## Commands executed

- `{test_result["command"]}` in `{test_result["cwd"]}`

## Test output

stdout:

```text
{stdout_block}
```

stderr:

```text
{stderr_block}
```

## Final result

{final_status}

## Limitations

{limitations_text}

## Next improvements

{next_improvements}
"""
    MARKDOWN_REPORT.write_text(markdown, encoding="utf-8")
    return data


def main() -> int:
    """Run the full demo and return a process status code."""
    reset_output_dir()
    choice = choose_provider()
    files_created = write_project_files()
    flow = run_agent_flow(choice, files_created)
    report = write_reports(choice=choice, flow=flow, files_created=files_created)

    print(f"Provider used: {choice.label}")
    print(f"Model used: {choice.model}")
    print(f"Generated project path: {OUTPUT_DIR}")
    print(f"Markdown report: {MARKDOWN_REPORT}")
    print(f"JSON report: {JSON_REPORT}")
    print(f"Test result: {report['final_status']}")
    return 0 if report["final_status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
