#include <handoffkit/demos/cases.hpp>

namespace handoffkit {
namespace demos {
namespace {

DemoCase C(
    const char* id,
    const char* domain,
    const char* title,
    const char* task,
    const char* context,
    std::vector<std::string> constraints,
    std::vector<std::string> success,
    std::vector<std::string> decisions,
    std::vector<std::string> files,
    int difficulty
) {
    DemoCase c;
    c.id = id;
    c.domain = domain;
    c.title = title;
    c.task = task;
    c.context = context;
    c.constraints = std::move(constraints);
    c.success_criteria = std::move(success);
    c.seed_decisions = std::move(decisions);
    c.seed_files = std::move(files);
    c.difficulty = difficulty;
    return c;
}

std::vector<DemoCase> build_corpus() {
    // Compact unique offline scenarios (no combinatorial variants).
    return {
        C("support-01-v1", "support", "Billing duplicate charge",
          "Customer reports two charges for the same invoice after a failed webhook retry. Include explicit next steps and owners.",
          "Support escalation offline; ticket tools available.",
          {"Remain offline", "Emit snake_case reports", "Record SLA risk"},
          {"Non-empty final_output", "Structured handoffs L1→L2→IC", "Ticket/SLA tool evidence in report"},
          {"Treat as P1 billing integrity", "Prefer hybrid_state handoffs"},
          {"tickets/T-1001.json", "reports/support.json"}, 3),
        C("support-02", "support", "SSO login loop",
          "Enterprise users stuck in redirect loop after IdP certificate rotation. Produce mitigation and comms handoff.",
          "IdP metadata changed; offline runbook only.",
          {"No live IdP calls", "Document rollback criteria"},
          {"Handoffs include next_steps", "Comms agent produces customer-safe summary"},
          {"Rotate cert with dual-publish window", "Keep old cert until sessions drain"},
          {"runbooks/sso.md"}, 4),
        C("support-03", "support", "Export job stuck",
          "Nightly CSV export remains running for 6 hours. Diagnose queue lag and owner handoff.",
          "Ops + support joint ownership.",
          {"Offline metrics only", "Include important_files for logs"},
          {"Priority score recorded", "Checklist coverage for mitigation"},
          {"Throttle producers", "Scale consumers temporarily"},
          {"logs/export-worker.txt"}, 3),
        C("coding-01", "coding", "Divide-by-zero calculator",
          "CLI calculator panics on /0; need pure functions, tests, and review handoff.",
          "Coding review showcase seed.",
          {"Use lint/diff tools", "Offline Echo providers"},
          {"Lint finds TODO", "Reviewer→Maintainer handoff exists"},
          {"Return Result error on zero divisor", "Add unit tests"},
          {"calc.cpp", "tests/test_calc.cpp"}, 2),
        C("coding-02", "coding", "Windows path packaging",
          "Path joins break when mixing slash styles in packaging scripts. Produce fix plan handoff.",
          "CMake/CLI packaging on Windows.",
          {"Prefer std::filesystem", "Keep demos offline"},
          {"Files list includes CMake and scripts", "Next steps are action verbs"},
          {"Normalize paths with filesystem::path", "Add path join tests"},
          {"CMakeLists.txt", "scripts/package_release.ps1"}, 3),
        C("coding-03", "coding", "Race in cache invalidation",
          "Stale reads after concurrent writes to shared map. Design lock strategy and tests.",
          "Multi-threaded service note (offline analysis).",
          {"No live load test", "Document thread-safety assumptions"},
          {"Handoff lists decisions and errors risks", "Quality score runnable"},
          {"Use shared_mutex or channel", "Add stress unit test"},
          {"src/cache.cpp"}, 4),
        C("research-01-v1", "research", "Competitive pricing scan",
          "Summarize public pricing tiers for three vendors with citations. Include explicit next steps and owners.",
          "Research workflow offline notes.",
          {"Keyword extract allowed", "No network fetch"},
          {"Editor produces executive summary", "Compressed protocol acceptable"},
          {"Capture tiers in decisions", "Cite offline notes only"},
          {"notes/pricing.md"}, 2),
        C("research-02", "research", "Protocol comparison",
          "Compare hybrid_state vs compressed handoff tradeoffs for CLI demos and packaging docs.",
          "Protocol matrix companion case.",
          {"Stay deterministic", "snake_case reports"},
          {"Matrix covers four modes", "Recommendations list present"},
          {"Prefer hybrid_state for support", "Use compressed for research digests"},
          {"docs/protocols.md"}, 2),
        C("clinical-01-v1", "clinical", "Chest pain triage vignette",
          "Offline panel ranks differentials given vitals and ECG text without live models.",
          "Doctor panel offline vignette.",
          {"Educational offline only", "No real PHI"},
          {"Three specialists run", "Quality on handoffs"},
          {"Rule out life threats first", "Document red flags"},
          {"vignettes/chest_pain.md"}, 4),
        C("clinical-02", "clinical", "Discharge checklist handoff",
          "Ensure handoff includes meds, follow-ups, and red flags for care transition.",
          "Care transition summary case.",
          {"Checklist tool required", "Offline only"},
          {"Checklist missing items listed", "Scribe handoff complete"},
          {"Meds reconciled", "PCP follow-up scheduled"},
          {"forms/discharge.md"}, 3),
        C("product-01-v1", "product", "PRD for export API",
          "Define goals, non-goals, and acceptance for async exports; hand off to engineering.",
          "Product spec handoff seed.",
          {"PM→Designer→TechLead", "Acceptance tests explicit"},
          {"Two+ handoffs", "final_output non-empty"},
          {"Async job status API", "Idempotent create"},
          {"prd/export-api.md"}, 3),
        C("product-02", "product", "Admin RBAC matrix",
          "Specify roles vs permissions for billing and support seats with engineering handoff.",
          "RBAC product case.",
          {"No live auth provider", "Document deny-by-default"},
          {"Decisions list roles", "Files include matrix path"},
          {"Separate billing admin from support", "Audit log required"},
          {"spec/rbac.md"}, 3),
        C("ops-01-v1", "ops", "SEV-1 auth outage",
          "Coordinate comms, mitigation, and handoff to oncall owners. Include explicit next steps and owners.",
          "Incident response showcase seed.",
          {"Priority score 5x5", "Checklist for comms/mitigation"},
          {"Oncall→Comms→Scribe", "Artifacts written when enabled"},
          {"Fail closed on auth", "Customer update within 30m"},
          {"runbooks/auth-outage.md"}, 5),
        C("ops-02", "ops", "Certificate expiry window",
          "Plan rotation without dropping mutual TLS clients; offline runbook rehearsal.",
          "Ops certificate rotation.",
          {"Dual cert publish", "No production calls"},
          {"Handoff lists important_files", "Next steps actionable"},
          {"Publish new cert first", "Revoke after drain"},
          {"certs/rotation.md"}, 4),
        C("ops-03", "ops", "Queue lag incident",
          "Consumer lag crosses SLO; propose throttle and scale with decision log.",
          "Queue lag offline analysis.",
          {"Use priority_score tool", "Record errors_checked"},
          {"Team final_output non-empty", "Quality evaluable"},
          {"Throttle ingress 50%", "Autoscale consumers"},
          {"metrics/queue-lag.json"}, 3),
        C("support-04", "support", "Rate limit false positives",
          "Legitimate batch API traffic hits 429 after deploy. Produce support-to-eng handoff.",
          "Post-deploy rate limit case.",
          {"Include deploy window context", "Offline only"},
          {"Handoff has context_refs", "SLA tool used if relevant"},
          {"Raise burst limit for batch clients", "Add allowlist for jobs"},
          {"deploy/notes.md"}, 3),
        C("coding-04", "coding", "Missing timeout budget",
          "Downstream call has no deadline; hangs saturate workers. Design timeout budget handoff.",
          "Reliability coding case.",
          {"Document budgets in decisions", "Tests for cancel path"},
          {"Reviewer lists risks in errors", "Maintainer merge conditions"},
          {"Default 2s timeout", "Propagate cancel tokens"},
          {"src/http_client.cpp"}, 4),
        C("research-03", "research", "Eval harness design",
          "Design offline eval cases for multi-agent handoff quality metrics.",
          "Eval research case.",
          {"Use existing quality metrics", "No network"},
          {"Editor summary references metrics names", "Keywords extracted"},
          {"completeness/clarity/actionability", "Golden handoff fixtures"},
          {"eval/design.md"}, 3),
        C("product-03", "product", "Marketplace listing draft",
          "Write listing bullets for handoffkit C++ package with eng feasibility handoff.",
          "Go-to-market product case.",
          {"Offline copy only", "Link to CLI demos"},
          {"PM handoff to TechLead", "Acceptance includes CLI demo list"},
          {"Lead with offline multi-agent", "Mention CMake/Conan"},
          {"gtm/listing.md"}, 2),
        C("clinical-03", "clinical", "Sepsis screen checklist",
          "Apply offline checklist-style screen to vignette facts and hand off next steps.",
          "Clinical checklist case.",
          {"Educational only", "Checklist tool"},
          {"Missing items reported", "Moderator consolidates"},
          {"Escalate if multiple positives", "Document vitals source"},
          {"vignettes/sepsis.md"}, 4),
        C("support-05", "support", "Webhook signature failures",
          "Partner integration rejects signatures after secret rotation. Support→eng escalation.",
          "Webhook signature offline case.",
          {"No partner API calls", "Record rotation timeline"},
          {"Ticket lookup optional", "Next owner named"},
          {"Dual-sign during rotation", "Publish secret version header"},
          {"integrations/webhooks.md"}, 3),
        C("coding-05", "coding", "Schema migration hazard",
          "Nullable column change breaks old readers during deploy. Migration handoff plan.",
          "Expand/contract migration case.",
          {"Two-phase deploy", "Rollback criteria"},
          {"Decisions include expand/contract", "Files list migration scripts"},
          {"Add column nullable first", "Backfill then enforce"},
          {"db/migrations/"}, 4),
        C("ops-04", "ops", "Backup restore test",
          "Validate RPO/RTO with staged restore checklist and scribe handoff.",
          "DR drill offline.",
          {"Checklist tool", "No production restore"},
          {"Checklist coverage computed", "Scribe records follow-ups"},
          {"Quarterly restore drill", "Document RPO 15m"},
          {"dr/restore.md"}, 3),
        C("research-04", "research", "Threat model outline",
          "Map trust boundaries for CLI tool execution and report writers offline.",
          "Security research case.",
          {"No live scanning", "snake_case report"},
          {"Analyst clusters boundaries", "Editor exec summary"},
          {"Tools stay workspace-scoped", "Reports may contain task text"},
          {"security/threat-model.md"}, 3),
        C("product-04", "product", "SLA dashboard requirements",
          "Define tiles for breach risk and aging tickets; hand off to eng.",
          "Dashboard product case.",
          {"Offline metrics definitions", "Acceptance tests"},
          {"Handoffs >= 2", "Files include dashboard spec"},
          {"Tile: aging by priority", "Tile: breach risk"},
          {"spec/sla-dashboard.md"}, 3),
        C("support-06", "support", "GDPR deletion backlog",
          "Deletion requests queue grows after storage migration. Compliance support handoff.",
          "Privacy ops/support case.",
          {"No real user data", "Track backlog age"},
          {"IC path if SLA breached", "Next steps legal+eng"},
          {"Prioritize oldest requests", "Add deletion worker metrics"},
          {"privacy/deletion.md"}, 4),
        C("coding-06", "coding", "Insecure temp file",
          "World-readable temp artifacts in multi-user CI. Hardening review handoff.",
          "Security coding case.",
          {"Lint stub optional", "Recommend restrictive perms"},
          {"Maintainer blocks merge until fixed", "errors list risk"},
          {"Use private temp dirs", "Delete on success"},
          {"src/temp_files.cpp"}, 3),
        C("ops-05", "ops", "Cost anomaly spike",
          "Attribute egress cost jump to misconfigured mirror; offline attribution handoff.",
          "FinOps ops case.",
          {"Offline cost notes", "Priority scoring"},
          {"Comms draft internal note", "Scribe follow-ups"},
          {"Disable bad mirror", "Add cost alert"},
          {"finops/egress.md"}, 3),
        C("clinical-04", "clinical", "Allergy documentation gap",
          "Handoff must capture NKDA vs unknown allergy status for transition of care.",
          "Documentation clinical case.",
          {"No PHI", "Explicit unknown vs NKDA"},
          {"Validation warns empty summary", "Quality recommendations useful"},
          {"Never assume NKDA", "Prompt clinician confirmation"},
          {"forms/allergies.md"}, 2),
        C("research-05", "research", "Docs IA proposal",
          "Propose information architecture for multi-runtime handoff kit docs.",
          "Docs research case.",
          {"Offline only", "Map CLI + CMake + Python"},
          {"Editor produces outline", "Keywords extracted from notes"},
          {"Top-level: quickstart, CLI, contracts, packages", "Cross-link wire format"},
          {"docs/ia.md"}, 2),
        C("product-05", "product", "SDK DX review",
          "List friction points in first 15 minutes of C++ install and hand off fixes.",
          "DX product case.",
          {"Mention FetchContent and Conan", "CLI demo as acceptance"},
          {"TechLead milestones listed", "final_output non-empty"},
          {"One-command CLI demo", "Install smoke consumer"},
          {"dx/sdk-review.md"}, 3),
        C("ops-06", "ops", "DNS scare validation",
          "Validate resolver path checks and document offline verification steps.",
          "DNS incident-style ops case.",
          {"No dig against prod", "Checklist of verifications"},
          {"Oncall mitigation notes", "Scribe decisions"},
          {"Check resolver config", "Document TTL assumptions"},
          {"net/dns.md"}, 3),
        C("coding-07", "coding", "Incomplete error mapping",
          "gRPC codes not translated to HTTP for gateway clients. Mapping design handoff.",
          "API coding case.",
          {"Table of code mappings in decisions", "Tests required"},
          {"Reviewer lists missing mappings", "Maintainer acceptance"},
          {"Map DEADLINE_EXCEEDED to 504", "Default 500 for unknown"},
          {"gateway/errors.cpp"}, 3),
        C("support-07", "support", "Seat license mismatch",
          "Admin cannot assign seats purchased via reseller. Billing support handoff.",
          "License support case.",
          {"Offline catalog only", "No payment network"},
          {"Ticket evidence", "Next steps billing eng"},
          {"Reconcile seat entitlements", "Add reseller channel flag"},
          {"billing/seats.md"}, 3),
        C("research-06", "research", "Model selection matrix offline",
          "Build offline matrix of cost/latency/quality for Echo baselines in demos.",
          "Provider research offline.",
          {"Echo only", "No API keys"},
          {"Matrix in final_output or report", "Editors summarize tradeoffs"},
          {"Echo for CI", "HTTP provider optional flag"},
          {"research/models.md"}, 2),
        C("product-06", "product", "Accessibility audit plan",
          "WCAG checks for report HTML templates; hand off remediation plan.",
          "A11y product case.",
          {"HTML reports in scope", "Offline checklist"},
          {"Checklist coverage", "TechLead remediation steps"},
          {"Color contrast tokens", "Keyboard focus order"},
          {"a11y/plan.md"}, 3),
        C("ops-07", "ops", "Secret sprawl cleanup",
          "Inventory leaked env keys in CI notes and rotate offline plan.",
          "Secrets ops case.",
          {"No real secrets in repo", "Rotation checklist"},
          {"Priority critical for exposed keys", "Comms internal only"},
          {"Rotate CI tokens", "Block long-lived secrets"},
          {"security/secrets.md"}, 5),
        C("clinical-05", "clinical", "Lab trend interpretation",
          "Summarize rising creatinine across three samples into structured handoff.",
          "Lab trend educational case.",
          {"No real patient data", "Structured decisions"},
          {"Panel handoffs", "Quality evaluable"},
          {"Flag acute rise", "Suggest nephrology if criteria met"},
          {"vignettes/labs.md"}, 3),
        C("coding-08", "coding", "Feature flag default-on",
          "Flag defaults to on in release builds accidentally. Fix and review handoff.",
          "Feature flag coding case.",
          {"Default off in release", "Tests for default"},
          {"Lint optional", "Maintainer blocks until default fixed"},
          {"Default false in release", "Explicit opt-in"},
          {"src/flags.cpp"}, 2),
        C("support-08", "support", "Mobile push not delivered",
          "iOS push tokens invalidate silently after app update. Support investigation handoff.",
          "Mobile support case.",
          {"Offline token notes", "No APNs calls"},
          {"L2 deep-dive", "Eng next steps"},
          {"Force token refresh", "Track invalidation rate"},
          {"mobile/push.md"}, 3),
    };
}

}  // namespace

const std::vector<DemoCase>& case_corpus() {
    static const std::vector<DemoCase> kCases = build_corpus();
    return kCases;
}

const DemoCase* find_case(std::string_view id) {
    for (const auto& c : case_corpus()) {
        if (c.id == id) {
            return &c;
        }
    }
    return nullptr;
}

std::vector<const DemoCase*> cases_for_domain(std::string_view domain) {
    std::vector<const DemoCase*> out;
    for (const auto& c : case_corpus()) {
        if (c.domain == domain) {
            out.push_back(&c);
        }
    }
    return out;
}

std::size_t case_corpus_size() {
    return case_corpus().size();
}

}  // namespace demos
}  // namespace handoffkit
